### ISSUE TITLE
How can we calculate "cov" in fingerprint?

### ISSUE THREAD

**Issue by Freestyleyang** [LiYanStat/dacc#5]
Hi there, thank you for developing the amazing package on Optimal Fingerprinting. In the function "fingerprint", "cov" is defined as Weight matrix used in prewhitening process, can be estimate of covariance matrix or precision matrix. 

In the example dataset "simDat", there are 2 versions of "cov" available: UN, and ST. What is the difference between them? Could you provide an example on how to calculate the "cov"? Thank you.

**Comment by LiYanStat** [comment]
Hi, the package provides a function "Covest" for calculating the covariance matrix from a group of independent replicates via several regularized methods. Currently there are two options provided, "mv" for minimal variance estimator, "l2" for the linear shrinkage estimator, see the reference for more details.

As for the "cov" in the simulated data, the 2 versions mean the structure for the true covariance matrix. The "UN" is calculated from the true dataset using "mv" estimator. "ST" means a spatial-temporal covariance structure.
