### ISSUE TITLE
Tutorial or example?

### ISSUE THREAD

**Issue by Freestyleyang** [LiYanStat/dacc#6]
Hi There,

Thank you for developing the package. Is there any tutorial or example on how to use the package? Thanks.

**Comment by LiYanStat** [comment]
We are working on the document to introduce the functions. It will be available on GitHub shortly.

**Comment by Freestyleyang** [comment]
Great! Thank you for your reply and I look forward to the document.

**Comment by Freestyleyang** [comment]
Hi There,

Could you please share any updates regarding the tutorial on the package? Thank you.

**Comment by LiYanStat** [comment]
> Hi There,
> 
> Could you please share any updates regarding the tutorial on the package? Thank you.

The guidance for the functions will be out within this week.

**Comment by Freestyleyang** [comment]
That's great news! Thank you for your amazing work in developing the package.

**Comment by Freestyleyang** [comment]
Hi There,

I was wondering if there are any updates regarding the tutorial about the package? Thanks.
